version: '3.3'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ragul0506
      MYSQL_DATABASE: tododb
      MYSQL_USER: ragul
      MYSQL_PASSWORD: ragul0506
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: todo_app
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/tododb
      SPRING_DATASOURCE_USERNAME: ragul
      SPRING_DATASOURCE_PASSWORD: ragul0506
    depends_on:
      - mysql
    links:
      - mysql
